import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import { DEFAULT_LANGUAGE, type SupportedLanguage } from '@/lib/language-options'

type TranslationResource = Record<string, string>

const english: TranslationResource = {
  appName: 'Phola',
  quickExit: 'Quick Exit',
  selectLanguage: 'Select language',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  getStarted: 'Get Started',
  signInToContinue: 'Sign in to continue',
  welcomeBack: 'Welcome back',
  preferredMethod: 'Sign in with your preferred method',
  orContinueWith: 'Or continue with',
  createSecureAccount: 'Create your secure account',
  privateSecure: 'Private & Secure',
  privateSecureBody: 'Your data is encrypted and only you can access it',
  quickAccess: 'Quick Access',
  quickAccessBody: 'Use biometrics or PIN to unlock instantly',
  fullName: 'Full Name',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  realNameRequired: 'Please enter your real name',
  passwordMismatch: 'Passwords do not match',
  passwordTooShort: 'Password must be at least 6 characters',
  pleaseTakeClearPhoto: 'Please take a clear photo or choose another image.',
  unexpectedError: 'An unexpected error occurred',
  profileUpdated: 'Profile updated successfully',
  profileUpdateFailed: 'Failed to update profile',
  biometricEnabled: 'Biometric login enabled',
  biometricDisabled: 'Biometric login disabled',
  biometricUnavailable: 'Biometric login is not available on this device',
  settingsTitle: 'Settings',
  languageTitle: 'Language',
  saveDraft: 'Save Draft',
  saveNote: 'Save Note',
  category: 'Category',
  whatHappened: 'What happened?',
  whenDidThisHappen: 'When did this happen?',
  locationOptional: 'Location (optional)',
  relationshipToPerson: 'Relationship to person involved',
  howSerious: 'How serious does this feel?',
  takeYourTime: 'Take your time. Only share what you feel comfortable with.',
  leaveWithoutSaving: 'Leave without saving?',
  stay: 'Stay',
  exitNow: 'Exit Now',
  emergencyHelp: 'Emergency Help',
  callEmergencyContact: 'Call Emergency Contact',
  shareMyLocation: 'Share My Location',
  sapsEmergency: 'SAPS Emergency (10111)',
  gbvHotline: 'GBV Hotline (0800 428 428)',
  emergency: 'Emergency (112)',
  findSafety: 'Find Safety',
  gettingLocation: 'Getting your location...',
  locationAccessRequired: 'Location Access Required',
  allowLocationAccess: 'Allow Location Access',
  noPlacesFound: 'No places found nearby',
  hospitals: 'Hospitals',
  police: 'Police',
  youAreHere: 'You are here',
  navigate: 'Navigate',
  offlineBanner: 'Offline mode - report will sync when connected',
  syncWhenConnected: 'Queued reports will sync when connected again.',
}

const shared = english

const resources: Record<SupportedLanguage, { translation: TranslationResource }> = {
  en: { translation: english },
  zu: { translation: { ...shared, quickExit: 'Phuma Masinyane', selectLanguage: 'Khetha ulimi', signIn: 'Ngena', signUp: 'Bhalisa', getStarted: 'Qala', signInToContinue: 'Ngena ukuze uqhubeke', welcomeBack: 'Uyemukelwa futhi', preferredMethod: 'Ngena ngendlela oyithandayo', orContinueWith: 'Noma qhubeka ngo', createSecureAccount: 'Dala i-akhawunti yakho evikelekile', privateSecure: 'Kuyimfihlo futhi Kuvikelekile', privateSecureBody: 'Idatha yakho ifihliwe futhi nguwe kuphela ongayifinyelela', quickAccess: 'Ukufinyelela Ngokushesha', quickAccessBody: 'Sebenzisa i-biometric noma i-PIN ukuze uvule ngokushesha', fullName: 'Igama Eliphelele', email: 'I-imeyili', password: 'Iphasiwedi', confirmPassword: 'Qinisekisa Iphasiwedi', realNameRequired: 'Sicela ufake igama lakho langempela', passwordMismatch: 'Amaphasiwedi awahambisani', passwordTooShort: 'Iphasiwedi kufanele ibe nezinhlamvu okungenani ezi-6', pleaseTakeClearPhoto: 'Sicela uthathe isithombe esicacile noma ukhethe esinye.', unexpectedError: 'Kwenzeke iphutha elingalindelekile', profileUpdated: 'Iphrofayela ibuyekezwe ngempumelelo', profileUpdateFailed: 'Ukuvuselela iphrofayela kwehlulekile', biometricEnabled: 'Ukungena nge-biometric kuvuliwe', biometricDisabled: 'Ukungena nge-biometric kuvaliwe', biometricUnavailable: 'Ukungena nge-biometric akutholakali kulesi sixhobo', settingsTitle: 'Izilungiselelo', languageTitle: 'Ulimi', saveDraft: 'Gcina Uhlaka', saveNote: 'Gcina Inothi', category: 'Isigaba', whatHappened: 'Kwenzekeni?', whenDidThisHappen: 'Lokhu kwenzeke nini?', locationOptional: 'Indawo (uyazikhethela)', relationshipToPerson: 'Ubudlelwano nomuntu othintekayo', howSerious: 'Kubukeka kubi kangakanani lokhu?', takeYourTime: 'Thatha isikhathi sakho. Yabelana kuphela ngalokho okhululekile ngakho.', leaveWithoutSaving: 'Uyahamba ngaphandle kokulondoloza?', stay: 'Hlala', exitNow: 'Phuma Manje', emergencyHelp: 'Usizo Lwezimo Eziphuthumayo', callEmergencyContact: 'Shayela Othintana Naye Ezimeni Eziphuthumayo', shareMyLocation: 'Yabelana ngendawo yami', sapsEmergency: 'I-SAPS Emergency (10111)', gbvHotline: 'I-GBV Hotline (0800 428 428)', emergency: 'Ezimo Eziphuthumayo (112)', findSafety: 'Thola Ukuphepha', gettingLocation: 'Sithola indawo yakho...', locationAccessRequired: 'Ukufinyelela Indawo Kuyadingeka', allowLocationAccess: 'Vumela Ukufinyelela Indawo', noPlacesFound: 'Awekho amazwe atholakele eduze', hospitals: 'Izibhedlela', police: 'Amaphoyisa', youAreHere: 'Ulapha', navigate: 'Hamba', offlineBanner: 'Imodi engaxhunyiwe - umbiko uzovumelaniswa uma uxhumekile', syncWhenConnected: 'Imibiko elindile izovumelaniswa uma uxhumeka futhi.', } },
  xh: { translation: { ...shared, quickExit: 'Phuma ngokukhawuleza', selectLanguage: 'Khetha ulwimi', signIn: 'Ngena', signUp: 'Bhalisa', getStarted: 'Qalisa', signInToContinue: 'Ngena ukuze uqhubeke', welcomeBack: 'Wamkelekile kwakhona', preferredMethod: 'Ngena ngendlela oyithandayo', orContinueWith: 'Okanye uqhubeke nge', createSecureAccount: 'Yenza iakhawunti yakho ekhuselekileyo', privateSecure: 'Yabucala kwaye ikhuselekile', privateSecureBody: 'Idatha yakho ifihliwe kwaye nguwe kuphela onokuyifikelela', quickAccess: 'Ufikelelo olukhawulezayo', quickAccessBody: 'Sebenzisa i-biometric okanye i-PIN ukuvula ngokukhawuleza', fullName: 'Igama elipheleleyo', email: 'I-imeyile', password: 'Iphasiwedi', confirmPassword: 'Qinisekisa iphasiwedi', realNameRequired: 'Nceda ufake igama lakho lokwenyani', passwordMismatch: 'Iiphasiwedi azihambelani', passwordTooShort: 'Iphasiwedi kufuneka ibe nobuncinane beempawu ezi-6', pleaseTakeClearPhoto: 'Nceda uthathe ifoto ecacileyo okanye ukhethe omnye umfanekiso.', unexpectedError: 'Kwenzeke impazamo engalindelekanga', profileUpdated: 'Iprofayile ihlaziywe ngempumelelo', profileUpdateFailed: 'Ukuhlaziya iprofayile akuphumelelanga', biometricEnabled: 'Ukungena nge-biometric kuvuliwe', biometricDisabled: 'Ukungena nge-biometric kuvaliwe', biometricUnavailable: 'Ukungena nge-biometric akufumaneki kwesi sixhobo', settingsTitle: 'Useto', languageTitle: 'Ulwimi', saveDraft: 'Gcina uyilo', saveNote: 'Gcina inqaku', category: 'Udidi', whatHappened: 'Kwenzeke ntoni?', whenDidThisHappen: 'Kwenzeke nini oku?', locationOptional: 'Indawo (ngokuzikhethela)', relationshipToPerson: 'Ubudlelwane kumntu ochaphazelekayo', howSerious: 'Oku kubonakala kubi kangakanani?', takeYourTime: 'Thatha ixesha lakho. Yabelana kuphela ngento oziva ukhululekile ngayo.', leaveWithoutSaving: 'Uphuma ungagcinanga?', stay: 'Hlala', exitNow: 'Phuma ngoku', emergencyHelp: 'Uncedo olungxamisekileyo', callEmergencyContact: 'Fowunela unxibelelwano olungxamisekileyo', shareMyLocation: 'Yabelana ngendawo yam', sapsEmergency: 'I-SAPS Emergency (10111)', gbvHotline: 'I-GBV Hotline (0800 428 428)', emergency: 'Ungxamiseko (112)', findSafety: 'Fumana ukhuseleko', gettingLocation: 'Sifumana indawo yakho...', locationAccessRequired: 'Ukufikelela kwindawo kuyafuneka', allowLocationAccess: 'Vumela ukufikelela kwindawo', noPlacesFound: 'Akukho ndawo ifunyenweyo kufuphi', hospitals: 'Izibhedlele', police: 'Amapolisa', youAreHere: 'Ulapha', navigate: 'Hamba', offlineBanner: 'Imo engaxhunyiwe - ingxelo iya kuthunyelwa xa usunxibelelene', syncWhenConnected: 'Iingxelo ezigciniweyo ziya kudityaniswa xa usunxibelelene kwakhona.', } },
  af: { translation: { ...shared, quickExit: 'Vinnige uitgang', selectLanguage: 'Kies taal', signIn: 'Meld aan', signUp: 'Registreer', getStarted: 'Begin', signInToContinue: 'Meld aan om voort te gaan', welcomeBack: 'Welkom terug', preferredMethod: 'Meld aan met jou voorkeurmetode', orContinueWith: 'Of gaan voort met', createSecureAccount: 'Skep jou veilige rekening', privateSecure: 'Privaat en Veilig', privateSecureBody: 'Jou data is geïnkripteer en net jy kan toegang daartoe kry', quickAccess: 'Vinnige toegang', quickAccessBody: 'Gebruik biometrie of PIN om onmiddellik te ontsluit', fullName: 'Volle naam', email: 'E-pos', password: 'Wagwoord', confirmPassword: 'Bevestig wagwoord', realNameRequired: 'Voer asseblief jou regte naam in', passwordMismatch: 'Wagwoorde stem nie ooreen nie', passwordTooShort: 'Wagwoord moet ten minste 6 karakters wees', pleaseTakeClearPhoto: 'Neem asseblief ’n duidelike foto of kies ’n ander prent.', unexpectedError: 'Onverwagte fout het voorgekom', profileUpdated: 'Profiel suksesvol bygewerk', profileUpdateFailed: 'Kon nie profiel bywerk nie', biometricEnabled: 'Biometriese aanmelding geaktiveer', biometricDisabled: 'Biometriese aanmelding gedeaktiveer', biometricUnavailable: 'Biometriese aanmelding is nie op hierdie toestel beskikbaar nie', settingsTitle: 'Instellings', languageTitle: 'Taal', saveDraft: 'Stoor konsep', saveNote: 'Stoor nota', category: 'Kategorie', whatHappened: 'Wat het gebeur?', whenDidThisHappen: 'Wanneer het dit gebeur?', locationOptional: 'Plek (opsioneel)', relationshipToPerson: 'Verhouding tot betrokke persoon', howSerious: 'Hoe ernstig voel dit?', takeYourTime: 'Neem jou tyd. Deel net wat jy gemaklik mee is.', leaveWithoutSaving: 'Verlaat sonder om te stoor?', stay: 'Bly', exitNow: 'Verlaat nou', emergencyHelp: 'Noodhulp', callEmergencyContact: 'Bel noodkontak', shareMyLocation: 'Deel my ligging', sapsEmergency: 'SAPS Nood (10111)', gbvHotline: 'GBV-blitslyn (0800 428 428)', emergency: 'Nood (112)', findSafety: 'Vind veiligheid', gettingLocation: 'Besig om jou ligging te kry...', locationAccessRequired: 'Liggingstoegang benodig', allowLocationAccess: 'Laat liggingstoegang toe', noPlacesFound: 'Geen plekke naby gevind nie', hospitals: 'Hospitale', police: 'Polisie', youAreHere: 'Jy is hier', navigate: 'Navigeer', offlineBanner: 'Vanlyn modus - verslag sal sinkroniseer wanneer gekoppel', syncWhenConnected: 'Wagverslae sal sinkroniseer sodra jy weer koppel.', } },
  nso: { translation: { ...shared, quickExit: 'Tšwa ka pela', selectLanguage: 'Kgetha leleme', signIn: 'Tsena', signUp: 'Ngwadiša', getStarted: 'Thoma', signInToContinue: 'Tsena go tšwela pele', welcomeBack: 'Rea go amogela gape', preferredMethod: 'Tsena ka mokgwa wo o o ratago', orContinueWith: 'Goba tšwela pele ka', createSecureAccount: 'Hlola akhaonto ya gago ya polokego', privateSecure: 'Ka sephiri le Polokego', privateSecureBody: 'Data ya gago e patilwe gomme ke wena fela yo a ka e fihlelelago', quickAccess: 'Tsenelo ya ka pela', quickAccessBody: 'Šomiša biometric goba PIN go bula gatee', fullName: 'Leina ka botlalo', email: 'I-meile', password: 'Phasewete', confirmPassword: 'Netefatša phasewete', realNameRequired: 'Ka kgopelo tsenya leina la gago la nnete', passwordMismatch: 'Di-phasewete ga di swane', passwordTooShort: 'Phasewete e swanetše go ba le ditlhaka tše 6 goba go feta', pleaseTakeClearPhoto: 'Ka kgopelo nka senepe se se hlakilego goba kgetha setshwantsho se sengwe.', unexpectedError: 'Phoso ye e bego e sa letelwa e diregile', profileUpdated: 'Pofaele e mpshafaditšwe ka katlego', profileUpdateFailed: 'Go mpshafatša pofaele go hlophetše', biometricEnabled: 'Tsenelo ya biometric e buletšwe', biometricDisabled: 'Tsenelo ya biometric e tima', biometricUnavailable: 'Tsenelo ya biometric ga e hwetšwe sedirišweng se', settingsTitle: 'Disetting', languageTitle: 'Leleme', saveDraft: 'Boloka moralo', saveNote: 'Boloka tsebišo', category: 'Sehlopha', whatHappened: 'Go diregile eng?', whenDidThisHappen: 'Se se diregile neng?', locationOptional: 'Lefelo (ke boikgethelo)', relationshipToPerson: 'Tswalano le motho yo a amegago', howSerious: 'Se se bonala se le bohlokwa gakaakang?', takeYourTime: 'Tšea nako ya gago. Abelana fela ka seo o ikemišeditšego go se abelana.', leaveWithoutSaving: 'O tla tšwa o sa boloka?', stay: 'Dula', exitNow: 'Tšwa bjale', emergencyHelp: 'Thušo ya tšhoganetšo', callEmergencyContact: 'Letša le ge o le kwa tšhoganetšo', shareMyLocation: 'Abelana lefelo la ka', sapsEmergency: 'Tšhoganetšo ya SAPS (10111)', gbvHotline: 'Mohala wa GBV (0800 428 428)', emergency: 'Tšhoganetšo (112)', findSafety: 'Hwetša polokego', gettingLocation: 'Re hwetša lefelo la gago...', locationAccessRequired: 'Go fihlelela lefelo go a nyakega', allowLocationAccess: 'Dumelela go fihlelela lefelo', noPlacesFound: 'Ga go na mafelo a hwetšwago kgauswi', hospitals: 'Dihlare tša malwetsi', police: 'Maphodisa', youAreHere: 'O mo', navigate: 'Tsamaea', offlineBanner: 'Mokgwa wa offline - pego e tla romelwa ge o kgokagantšwe', syncWhenConnected: 'Dipego tše di emego di tla synca ge o kgokagantšwe gape.', } },
  tn: { translation: { ...shared, quickExit: 'Tswela pele ka pela', selectLanguage: 'Tlhopha puo', signIn: 'Tsena', signUp: 'Ingolisa', getStarted: 'Simolola', signInToContinue: 'Tsena go tswelela pele', welcomeBack: 'Rea go amogela gape', preferredMethod: 'Tsena ka mokgwa o o o ratang', orContinueWith: 'Kgotsa tswelela ka', createSecureAccount: 'Tlhama akhaonto ya gago e e sireletsegileng', privateSecure: 'Sephiri le Tshireletsego', privateSecureBody: 'Data ya gago e encrypted mme ke wena fela yo o ka e fitlhelang', quickAccess: 'Phitlhelelo ya ka bonako', quickAccessBody: 'Dirisa biometrics kgotsa PIN go bula ka bonako', fullName: 'Leina le feletseng', email: 'Imeile', password: 'Lefoko-pase', confirmPassword: 'Netefatsa lefoko-pase', realNameRequired: 'Tsweetswee tsenya leina la gago la nnete', passwordMismatch: 'Mafoko-pase ga a tshwane', passwordTooShort: 'Lefoko-pase le tshwanetse go nna le ditlhaka di le 6 kgotsa go feta', pleaseTakeClearPhoto: 'Tsweetswee tsaya setshwantsho se se phepa kgotsa tlhopa sengwe se sele.', unexpectedError: 'Go diragetse phoso e e sa lebelelwang', profileUpdated: 'Pofaele e ntšhafaditswe ka katlego', profileUpdateFailed: 'Go ntšhafatsa pofaele go paletswe', biometricEnabled: 'Go tsena ka biometric go dirilwe', biometricDisabled: 'Go tsena ka biometric go timilwe', biometricUnavailable: 'Go tsena ka biometric ga go teng mo sedirisweng seno', settingsTitle: 'Dipeo', languageTitle: 'Puo', saveDraft: 'Boloka moralo', saveNote: 'Boloka ntlha', category: 'Setlhopha', whatHappened: 'Go diragetse eng?', whenDidThisHappen: 'Se se diragetse leng?', locationOptional: 'Lefelo (ga se la tshwanelo)', relationshipToPerson: 'Kamano le motho yo o amegang', howSerious: 'Se se lebega se masisi go le kae?', takeYourTime: 'Tsa nako ya gago. Abelana fela ka se o ikutlwang o gololesegile ka sone.', leaveWithoutSaving: 'O tsamaya o sa boloka?', stay: 'Sala', exitNow: 'Tswa jaanong', emergencyHelp: 'Thuso ya Tshoganyetso', callEmergencyContact: 'Letsetsa motsoako wa tshoganyetso', shareMyLocation: 'Abelana lefelo la me', sapsEmergency: 'Tshoganyetso ya SAPS (10111)', gbvHotline: 'GBV Hotline (0800 428 428)', emergency: 'Tshoganyetso (112)', findSafety: 'Bona polokego', gettingLocation: 'Re bona lefelo la gago...', locationAccessRequired: 'Go tlhokega phitlhelelo ya lefelo', allowLocationAccess: 'Dumelela phitlhelelo ya lefelo', noPlacesFound: 'Ga go na mafelo a a fitlhelwang gaufi', hospitals: 'Dibedlele', police: 'Mapodisa', youAreHere: 'O fa', navigate: 'Tsamaya', offlineBanner: 'Mokgwa wa offline - pego e tla synca fa o kgokagantswe', syncWhenConnected: 'Dipego tse di letetseng di tla synca fa o kgokagantswe gape.', } },
  st: { translation: { ...shared, quickExit: 'Tsoa kapele', selectLanguage: 'Khetha puo', signIn: 'Kena', signUp: 'Ngodisa', getStarted: 'Qala', signInToContinue: 'Kena ho tsoela pele', welcomeBack: 'O amohelehile hape', preferredMethod: 'Kena ka mokhoa oo u o ratang', orContinueWith: 'Kapa tsoela pele ka', createSecureAccount: 'Theha akhaonto ea hao e sireletsehileng', privateSecure: 'Ea lekunutu ebile e Sireletsehile', privateSecureBody: 'Lintlha tsa hao li patiloe mme ke uena feela ea ka li fihlelang', quickAccess: 'Phihlello e Potlakileng', quickAccessBody: 'Sebedisa biometrics kapa PIN ho notlolla hang-hang', fullName: 'Lebitso le felletseng', email: 'Imeile', password: 'Phasewete', confirmPassword: 'Netefatsa phasewete', realNameRequired: 'Ka kopo kenya lebitso la hao la nnete', passwordMismatch: 'Li-phasewete ha li tšoane', passwordTooShort: 'Phasewete e lokela ho ba bonyane litlhaku tse 6', pleaseTakeClearPhoto: 'Ka kopo nka setšoantšo se hlakileng kapa khetha se seng.', unexpectedError: 'Ho etsahetse phoso e sa lebelloang', profileUpdated: 'Profaele e ntlafalitsoe ka katleho', profileUpdateFailed: 'Ho ntlafatsa profaele ho hlolehile', biometricEnabled: 'Ho kena ka biometric ho buletsoe', biometricDisabled: 'Ho kena ka biometric ho koetsoe', biometricUnavailable: 'Ho kena ka biometric ha ho fumanehe sesebelisoa sena', settingsTitle: 'Litlhophiso', languageTitle: 'Puo', saveDraft: 'Boloka moralo', saveNote: 'Boloka noutu', category: 'Sehlopha', whatHappened: 'Ho etsahetse eng?', whenDidThisHappen: 'Sena se etsahetse neng?', locationOptional: 'Sebaka (ka boikhethelo)', relationshipToPerson: 'Kamano le motho ea amehang', howSerious: 'Sena se bonahala se le matla hakae?', takeYourTime: 'Nka nako ea hao. Arolelana feela seo u phutholohileng ka sona.', leaveWithoutSaving: 'U tsoa u sa boloka?', stay: 'Lula', exitNow: 'Tsoa hona joale', emergencyHelp: 'Thuso ea Tšohanyetso', callEmergencyContact: 'Letsetsa motho ea ka thusang', shareMyLocation: 'Abelana sebaka sa ka', sapsEmergency: 'Tšohanyetso ea SAPS (10111)', gbvHotline: 'Mohala oa GBV (0800 428 428)', emergency: 'Tšohanyetso (112)', findSafety: 'Fumana polokeho', gettingLocation: 'Re fumana sebaka sa hao...', locationAccessRequired: 'Ho hlokahala phihlello ea sebaka', allowLocationAccess: 'Lumella phihlello ea sebaka', noPlacesFound: 'Ha ho libaka tse fumanoeng haufi', hospitals: 'Lipetlele', police: 'Mapolesa', youAreHere: 'U mona', navigate: 'Tsamaea', offlineBanner: 'Mokhoa oa offline - tlaleho e tla synca ha o hokahantsoe', syncWhenConnected: 'Litlaleho tse emetseng li tla synca ha o hokahantsoe hape.', } },
  ts: { translation: { ...shared, quickExit: 'Huma msinya', selectLanguage: 'Khetha ririmi', signIn: 'Nghena', signUp: 'Tibhalise', getStarted: 'Sungula', signInToContinue: 'Nghena ku ya emahlweni', welcomeBack: 'U amukelekile nakambe', preferredMethod: 'Nghena hi ndlela leyi u yi tsakelaka', orContinueWith: 'Kumbe emahlweni na', createSecureAccount: 'Endla account ya wena leyi sirhelelekeke', privateSecure: 'Swa xihundla naswona swa Sirheleleka', privateSecureBody: 'Data ya wena yi encrypted naswona hi wena ntsena loyi a nga yi fikelelaka', quickAccess: 'Ku fikelela hi xihatla', quickAccessBody: 'Tirhisa biometrics kumbe PIN ku pfula hi xihatla', fullName: 'Vito hinkwaro', email: 'Imeyili', password: 'Phasiwedi', confirmPassword: 'Tiyisisa phasiwedi', realNameRequired: 'Sicela u nghenisa vito ra wena ra ntiyiso', passwordMismatch: 'Tiwedi ta phasiwedi a ti fambelani', passwordTooShort: 'Phasiwedi yi fanele yi va na swihlamusi swa 6 kumbe ku tlula', pleaseTakeClearPhoto: 'Sicela teka foto leyi hlakaleke kumbe hlawula xin’wana.', unexpectedError: 'Ku humelele xihoxo lexi nga languteriwangiki', profileUpdated: 'Profayili yi pfuxetiwile hi ku humelela', profileUpdateFailed: 'Ku pfuxeta profayili ku tsandzekile', biometricEnabled: 'Ku nghena hi biometric ku pfurile', biometricDisabled: 'Ku nghena hi biometric ku pfariwile', biometricUnavailable: 'Ku nghena hi biometric a ku kumeki eka xitirhisiwa lexi', settingsTitle: 'Switirhisiwa', languageTitle: 'Ririmi', saveDraft: 'Hlayisa draft', saveNote: 'Hlayisa noti', category: 'Xiyenge', whatHappened: 'Ku humelerile yini?', whenDidThisHappen: 'Leswi swi humelerile rini?', locationOptional: 'Ndhawu (swi nga hlawuriwa)', relationshipToPerson: 'Nchumu exikarhi ka wena na munhu loyi a khumbekaka', howSerious: 'Leswi swi vonaka swi ri swa nkoka njhani?', takeYourTime: 'Teka nkarhi wa wena. Avelana ntsena leswi u titwisaka kahle ka swona.', leaveWithoutSaving: 'U suka u nga hlayisanga?', stay: 'Tshama', exitNow: 'Humani sweswi', emergencyHelp: 'Mpfuneto wa xihatla', callEmergencyContact: 'Fonela munhu wa xihatla', shareMyLocation: 'Avelana ndhawu ya mina', sapsEmergency: 'SAPS Emergency (10111)', gbvHotline: 'GBV Hotline (0800 428 428)', emergency: 'Xihatla (112)', findSafety: 'Kuma vuhlayiseki', gettingLocation: 'Hi kuma ndhawu ya wena...', locationAccessRequired: 'Ku fikelela ndhawu ku a laveka', allowLocationAccess: 'Pfumelela ku fikelela ndhawu', noPlacesFound: 'A ku na tindhawu leti kumiwa ekusuhi', hospitals: 'Swibedlela', police: 'Maphorisa', youAreHere: 'U laha', navigate: 'Yendla ndlela', offlineBanner: 'Offline mode - report will sync when connected', syncWhenConnected: 'Mimbiko leyi rindzeleke yi ta synca loko u tlhela u hlanganisiwa.', } },
  ss: { translation: { ...shared, quickExit: 'Phuma masinyane', selectLanguage: 'Khetsa lulwimi', signIn: 'Ngena', signUp: 'Bhalisa', getStarted: 'Cala', signInToContinue: 'Ngena kutsi uchubeke', welcomeBack: 'Uyemukelwa futsi', preferredMethod: 'Ngena ngendlela loyikhetsile', orContinueWith: 'Noma uchubeke nge', createSecureAccount: 'Yakha i-akhawunti yakho lephephile', privateSecure: 'Lihlolelekile futsi Livikelekile', privateSecureBody: 'Idatha yakho ifihlakele futsi nguwe kuphela longayifinyelela', quickAccess: 'Kufinyelela ngesivinini', quickAccessBody: 'Sebentisa i-biometric kumbe i-PIN kutsi uvule masinyane', fullName: 'Ligama lonkhe', email: 'I-imeyili', password: 'Liphasiphothi', confirmPassword: 'Cinisekisa liphasiphothi', realNameRequired: 'Ngicela ufake ligama lakho leliciniso', passwordMismatch: 'Tivumelani tekuphasiphothi atihambisani', passwordTooShort: 'Liphasiphothi kumele libe netincetu letingu-6 kumbe kute la', pleaseTakeClearPhoto: 'Ngicela uthathe sithombe lesicacile kumbe ukhetsa lesinye.', unexpectedError: 'Kwenteke liphutsa lelingalindzeleka', profileUpdated: 'Iphrofayili ibuyeketiwe kahle', profileUpdateFailed: 'Kuvuselela iphrofayili kwehlulekile', biometricEnabled: 'Kungena nge-biometric kuvuliwe', biometricDisabled: 'Kungena nge-biometric kuvaliwe', biometricUnavailable: 'Kungena nge-biometric akutholakali kulomshini', settingsTitle: 'Lungisa', languageTitle: 'Lulwimi', saveDraft: 'Gcina umdvwebo', saveNote: 'Gcina inothi', category: 'Sigaba', whatHappened: 'Kwentekeni?', whenDidThisHappen: 'Lokhu kwenteke nini?', locationOptional: 'Indzawo (ngekutikhetsela)', relationshipToPerson: 'Budlelwane nemuntfu loginile', howSerious: 'Lokhu kubukeka kubi kangakanani?', takeYourTime: 'Tsatsa sikhatsi sakho. Wabelane kuphela ngaloko lotiva ukhululekile ngako.', leaveWithoutSaving: 'Uyaphuma ungakagcini?', stay: 'Hlala', exitNow: 'Phuma manje', emergencyHelp: 'Lusito lwetimphilo letiphuthumako', callEmergencyContact: 'Shayela lucingo loluphuthumako', shareMyLocation: 'Wabelana ngendawo yami', sapsEmergency: 'SAPS Emergency (10111)', gbvHotline: 'GBV Hotline (0800 428 428)', emergency: 'Emergency (112)', findSafety: 'Tfola kuphepha', gettingLocation: 'Sitfola indzawo yakho...', locationAccessRequired: 'Kufinyelela endzaweni kuyadingeka', allowLocationAccess: 'Vumela kufinyelela endzaweni', noPlacesFound: 'Akukho tindzawo letitfolakele edvute', hospitals: 'Tibhedlela', police: 'Amaphoyisa', youAreHere: 'Ulapha', navigate: 'Hambisa', offlineBanner: 'Offline mode - umbiko utawuvumelaniswa uma usuxhumekile', syncWhenConnected: 'Imibiko lemile itawuvumelaniswa uma usuxhumeka futsi.', } },
  ve: { translation: { ...shared, quickExit: 'Bvela u itamisa', selectLanguage: 'Nangani luambo', signIn: 'Dzhena', signUp: 'Ṅwala', getStarted: 'Thomani', signInToContinue: 'Dzhena u bvela phanda', welcomeBack: 'Ni a andadzwa hafhu', preferredMethod: 'Dzhena nga ndila ine na i funa', orContinueWith: 'Kana ni bvela na', createSecureAccount: 'Vhumbani account yanu yo tsireledzea', privateSecure: 'Zwa secrete na zwine zwa tsireledzea', privateSecureBody: 'Data yanu yo khouthedzwa nahone ndi inwi fhedzi ane a nga i swikelela', quickAccess: 'U swikelela nga u ṱavhanya', quickAccessBody: 'Shumisani biometrics kana PIN u vula nga u ṱavhanya', fullName: 'Dzina lo fhelelaho', email: 'Imeyili', password: 'Phasiwede', confirmPassword: 'Khwaṱhisedzani phasiwede', realNameRequired: 'Ri humbela uri ni ṱale dzina lanu la vhukuma', passwordMismatch: 'Phasiwede a dzi tshaana', passwordTooShort: 'Phasiwede i fanela u vha na mitalo i ṱanganyiswaho ya 6 kana u fhira', pleaseTakeClearPhoto: 'Ri humbela uri ni vhulunge foto i bvelelaho kana ni nange iṅwe tshifanyiso.', unexpectedError: 'Ho bvelela phoswo i sa lavhelelwaho', profileUpdated: 'Phrofaili yo khwinifhadzwa zwavhuḓi', profileUpdateFailed: 'U khwinifhadza phrofaili ho kundelwa', biometricEnabled: 'U dzhena nga biometric ho vulelwa', biometricDisabled: 'U dzhena nga biometric ho valelwa', biometricUnavailable: 'U dzhena nga biometric a hu wanali kha tshishumiswa tshino', settingsTitle: 'Zwinwe zwithu', languageTitle: 'Luambo', saveDraft: 'Vhulunga draft', saveNote: 'Vhulunga noutsi', category: 'Tshigwada', whatHappened: 'Ho bvelelani?', whenDidThisHappen: 'Izwi zwo bvelela lini?', locationOptional: 'Fhethu (ni nga si kone)', relationshipToPerson: 'Vhukonani na muthu o kwameswaho', howSerious: 'Izwi zwi vhonala zwi zwa vhuhulu hani?', takeYourTime: 'Dzhiani tshifhinga tshaṋu. Abelanani fhedzi zwine na khou phuthudzwa ngazwo.', leaveWithoutSaving: 'Ni bvela nnḓa ni songo vhulunga?', stay: 'Dzula', exitNow: 'Bvelani zwino', emergencyHelp: 'Thuso ya tshanḓa tsha phanḓa', callEmergencyContact: 'Founela mutshimbidzi wa tshanḓa tsha phanḓa', shareMyLocation: 'Abelanani fhethu hanga', sapsEmergency: 'SAPS Emergency (10111)', gbvHotline: 'GBV Hotline (0800 428 428)', emergency: 'Emergency (112)', findSafety: 'Wanani tshireledzo', gettingLocation: 'Ri khou wana fhethu haṋu...', locationAccessRequired: 'U swikelela fhethu hu a lavhelea', allowLocationAccess: 'Tenderani u swikelela fhethu', noPlacesFound: 'A hu na fhethu ho wanalaho tsini', hospitals: 'Mavhidzo', police: 'Mapholisa', youAreHere: 'Ni fhano', navigate: 'Livhuwani', offlineBanner: 'Offline mode - mbiko i do synca musi ni tshi vhanda', syncWhenConnected: 'Mbiko dzine dza lindela dzi do synca musi ni tshi dovha na vhanda.', } },
  nr: { translation: { ...shared, quickExit: 'Phuma masinyane', selectLanguage: 'Khetha ilimi', signIn: 'Ngena', signUp: 'Bhalisa', getStarted: 'Qala', signInToContinue: 'Ngena bona uqhubeke', welcomeBack: 'Uyamukeleka godu', preferredMethod: 'Ngena ngendlela oyithandako', orContinueWith: 'Namkha qhubeka nge', createSecureAccount: 'Yakha i-akhawunti yakho ephephileko', privateSecure: 'Sasese begodu Sivikelekile', privateSecureBody: 'Idatha yakho ifihlakele begodu nguwe kuphela ongayifikelela', quickAccess: 'Ukufikelela msinyana', quickAccessBody: 'Sebenzisa i-biometric nanyana i-PIN bona uvule msinyana', fullName: 'Ibizo elipheleleko', email: 'I-imeyili', password: 'Iphaswedi', confirmPassword: 'Qinisekisa iphaswedi', realNameRequired: 'Sicela ufake ibizo lakho langempela', passwordMismatch: 'Amaphaswedi awafani', passwordTooShort: 'Iphaswedi kumele ibe nezinhlamvu eziphasi kwe-6 nanyana ngaphezulu', pleaseTakeClearPhoto: 'Sicela uthathe isithombe esicacile nanyana ukhethe esinye isithombe.', unexpectedError: 'Kwenzeke iphutha elingalindelekileko', profileUpdated: 'Iphrofayili ibuyekezwe ngempumelelo', profileUpdateFailed: 'Ukuvuselela iphrofayili kwehlulekile', biometricEnabled: 'Ukungena nge-biometric kuvuliwe', biometricDisabled: 'Ukungena nge-biometric kuvaliwe', biometricUnavailable: 'Ukungena nge-biometric akutholakali kulesi sithuthi', settingsTitle: 'Amasethingi', languageTitle: 'Ulimi', saveDraft: 'Gcina umdwebo', saveNote: 'Gcina inothi', category: 'Isigaba', whatHappened: 'Kwenzekeni?', whenDidThisHappen: 'Lokhu kwenzeke nini?', locationOptional: 'Indawo (uyazikhethela)', relationshipToPerson: 'Ubudlelwano nomuntu othintekako', howSerious: 'Lokhu kubonakala kubi kangangani?', takeYourTime: 'Thatha isikhathi sakho. Yabelana ngalokho ozizwa ukhululekile ngakho kuphela.', leaveWithoutSaving: 'Uyaphuma ngaphandle kokugcina?', stay: 'Hlala', exitNow: 'Phuma manje', emergencyHelp: 'Usizo oluphuthumako', callEmergencyContact: 'Shayela isibizo esiphuthumako', shareMyLocation: 'Yabelana ngendawo yami', sapsEmergency: 'I-SAPS Emergency (10111)', gbvHotline: 'I-GBV Hotline (0800 428 428)', emergency: 'Emergency (112)', findSafety: 'Thola ukuphepha', gettingLocation: 'Sithola indawo yakho...', locationAccessRequired: 'Ukufikelela endaweni kuyadingeka', allowLocationAccess: 'Vumela ukufikelela endaweni', noPlacesFound: 'Akunandawo etholakele eduze', hospitals: 'Izibhedlela', police: 'Amapholisa', youAreHere: 'Ulapha', navigate: 'Hambisa', offlineBanner: 'Offline mode - umbiko uzovumelaniswa nakube uxhumekile', syncWhenConnected: 'Imibiko esalindile izovumelaniswa nakube usuxhume godu.', } },
}

export const supportedLanguages = Object.keys(resources) as SupportedLanguage[]

export async function initI18n() {
  if (i18n.isInitialized) {
    return i18n
  }

  await i18n.use(initReactI18next).init({
    resources,
    lng: DEFAULT_LANGUAGE,
    fallbackLng: DEFAULT_LANGUAGE,
    interpolation: {
      escapeValue: false,
    },
    returnEmptyString: false,
    load: 'languageOnly',
  })

  return i18n
}

export default i18n
